### ISSUE TITLE
pass logical arguments to widget

### ISSUE THREAD

**Issue by timelyportfolio** [Swechhya/excelR#4]
See #3 for praise and thanks for creating this package and also the apology for intruding.

Many logical arguments if `FALSE` are not passed to the `htmlwidget` as shown in [lines](https://github.com/Swechhya/excelR/blob/master/R/jexcel.R#L312-L380).

**Comment by Swechhya** [comment]
@timelyportfolio The logical arguments which have default values(whether it is `TRUE` or `FALSE`) as provided by `jExcel` has not been passed to the `htmlwidget`. But on second thought it seems better if we pass those values so that our library doesn't get affected  in case `jExcel` changes the default values.
