### ISSUE TITLE
Get/set comments from Shiny

### ISSUE THREAD

**Issue by marciz** [Swechhya/excelR#42]
Add function to get and set comments in excelTable in Shiny

**Comment by Swechhya** [comment]
In [`jexcel`](https://bossanova.uk/jexcel/v3/) we can easily set and get comments as mentioned [here](https://bossanova.uk/jexcel/v3/examples/comments). 

**Requirement:**
1. Add a parameter `allowComments`  in excelTable.
2. `allowComments` should be passed to `jexcel` so that user will be able to set comments.
3. Functions `setComments` and `getComments` should be added to the R side which will set and  get comments from the the `jexcel` table.
4. `setComments` function should take three parameters the table id, cell id and the comment to be added to the cell which would invoke the `setComments` function on the `js` side.
5. `getComments` function should take two parameters the table id and cell id which should invoke `getComments` function on the js side.

**Comment by Swechhya** [comment]
As PR #47  addresses this issue, closing this. Feel free to open it again in case of any discrepancy.
