### ISSUE TITLE
ExcelTable not showing when defining columns in dev build

### ISSUE THREAD

**Issue by mmoisse** [Swechhya/excelR#83]
**Describe the bug**
When I define columns in excelTable I do not get to see the table, only an empty page. Leaving out the column argument solves the issue.

**To Reproduce**
```
## Latest version a this point
devtools::install_github('Swechhya/excelR@9ff3edb1')

library(excelR)

data = data.frame(Model = c('Mazda', 'Pegeout', 'Honda Fit', 'Honda CRV'),
                  Date=c('2006-01-01', '2005-01-01','2004-01-01', '2003-01-01' ),
                  Availability = c(TRUE, FALSE, TRUE, TRUE))


columns = data.frame(title=c('Model', 'Date', 'Availability'),
                     width= c(300, 300, 300),
                     type=c('text', 'calendar', 'checkbox'))

excelTable(data=data, columns = columns)

```

**Expected behavior**
See the table

**Desktop (please complete the following information):**
 - OS: Linux
 - Version git version Swechhya/excelR@9ff3edb1

**Comment by Swechhya** [comment]
@mmoisse Thank you for reporting this critical bug. This bug was caused due to the inclusion of the `calendar` column type without `option` in the column parameter.  
This has now been fixed in the latest development version. Hence, closing this issue now. Feel free to open it if the issue persists.
